name: Valider merge queue

permissions:
  contents: read
  packages: read
  id-token: write

on:
  merge_group:
    types:
      - checks_requested

jobs:
  mq-test:
    name: MQ test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  mq-verdikjede:
    name: MQ verdikjede
    uses: ./.github/workflows/verdikjede.yml
    with:
      is-merge-queue: true
    secrets: inherit

  mq-storybook-test:
    name: MQ storybook-test
    uses: ./.github/workflows/storybook-tests.yml
    secrets: inherit

  mq-lint-tscheck-build:
    name: MQ lint-tscheck-build
    uses: ./.github/workflows/lint-tscheck-build.yml
    secrets: inherit
    with:
      run-build: true
